// Description: This file contains the text data for the website.
// Basic text strings are numbered 100-499 and are found in html data-txt_id attributes.
// Title attributes are numbered 500-599 and are found in html data-txt_id__title
// Alt attributes are numbered 600-699 and are found in html data-txt_id__alt

export const data_lang_nl = {
  document_lang: "nl",
  document_desc: "Website van Lion Digits, door Joris Raymaekers.",
  document_title: "Lion Digits, web ontwikkeling",
  pseudo_elem_001: "Gekopieerd!",
  100: "nl",
  101: "Nieuwe Titel Hier.",
  102: "Je website is dé weg naar méér klanten en inkomsten",
  103: "met LionDigits ga je sneller en verder.",
  104: "Maak een afspraak",
  501: "Foto van Joris Raymaekers",
  502: "JavaScript",
  503: "ReactJs",
  504: "TypeScript",
  505: "NodeJs",
  506: "Demo video van de Catacamp website",
  507: "Bezoek de Catacamp website",
  508: "Bekijk de code op GitHub",
  509: "Demo video van de Goudster website",
  510: "Bezoek de website van Goudster",
  511: "Homepagina Brasserie Lemmensmolen",
  512: "Bezoek de website van Brasserie Lemmensmolen",
  513: "Demo video van de Travel Agency website",
  514: "Bezoek de website van Clear View Escape",
  515: "Email Joris Raymaekers",
  516: "Bel mij vanuit België",
  517: "Bel mij vanuit Spanje",
  518: "Contacteer mij via de Signal Messenger App",
  519: "Contacteer mij via Skype",
  520: "Bekijk mijn profiel op Linked-In",
  521: "Bekijk mijn profiel op Twitter",
  522: "Bekijk de code die ik schrijf op Github",
  523: "Bekijk mijn visuele creaties op Codepen",
  524: "Kopiëren naar klembord",
  525: "Wat is dit?",
  526: "PGP introductie artikel",
  527: "Home",
  528: "Bezoek het MS-DOS Games Archive",
  529: "Lees het privacy-beleid",
  600: "Lion Digits logo",
  601: "Vertalen icoon",
  602: "Driehoek icoon",
  603: "Pyramide icoon",
  604: "Zandloper icoon",
  605: "Foto van Joris Raymaekers",
  606: "JavaScript logo",
  607: "ReactJs logo",
  608: "TypeScript logo",
  609: "NodeJs logo",
  610: "Demo video van de Catacamp website",
  611: "Catacamp logo",
  612: "externe link icoon",
  613: "Github logo",
  614: "Demo video van de Goudster website",
  615: "Goudster logo",
  616: "Homepagina Brasserie Lemmensmolen",
  617: "Lemmensmolen logo",
  618: "Demo video van de Travel Agency website",
  619: "Clear View Escape logo",
  620: "Email icoon",
  621: "Telefoon België icoon",
  622: "Telefoon Spanje icoon",
  623: "Signal Messenger App logo",
  624: "Skype logo",
  625: "Linked-In logo",
  626: "Twitter logo",
  627: "Codepen logo",
  628: "Kopiëren naar klembord icoon",
  629: "Vraagteken icoon",
  630: "Klik hier om de modal te sluiten",
  631: "Casa Pedrera Barcelona",
  632: "Doorbraak logo",
  633: "Codepen profiel snapshot",
  634: "Download icoon",
};
export const data_lang_en = {
  document_lang: "en",
  document_title: "Lion Digits, web development",
  document_desc: "Website Lion Digits, by Joris Raymaekers.",
  pseudo_elem_001: "Copied!",
  100: "en",
  101: "New Title Here.",
  102: "Your online presence is the gateway to more customers and revenue",
  103: "go further with Lion Digits.",
  104: "Book a meeting",
  501: "Foto of Joris Raymaekers",
  502: "JavaScript",
  503: "ReactJs",
  504: "TypeScript",
  505: "NodeJs",
  506: "Demo video of the Catacamp website",
  507: "Visit the Catacamp website",
  508: "View the code on GitHub",
  509: "Demo video of the Goudster website",
  510: "Visit the Goudster website",
  511: "Homepage Brasserie Lemmensmolen",
  512: "Visit the website of Brasserie Lemmensmolen",
  513: "Demo video of the Travel Agency website",
  514: "Visit the website of Clear View Escape",
  515: "Email Joris Raymaekers",
  516: "Call me from Belgium",
  517: "Call me from Spain",
  518: "Contact me via the Signal Messenger App",
  519: "Contact me via Skype",
  520: "View my profile on Linked-In",
  521: "View my profile on Twitter",
  522: "View the code I write on Github",
  523: "View my visual creations on Codepen",
  524: "Copy to clipboard",
  525: "What is this?",
  526: "PGP introduction article",
  527: "Home",
  528: "Visit the MS-DOS Games Archive",
  529: "Read the privacy policy",
  600: "Lion Digits logo",
  601: "Translate icon",
  602: "Triangle icon",
  603: "Pyramid icon",
  604: "Sandglass icon",
  605: "Foto of Joris Raymaekers",
  606: "JavaScript logo",
  607: "ReactJs logo",
  608: "TypeScript logo",
  609: "NodeJs logo",
  610: "Demo video of the Catacamp website",
  611: "Catacamp logo",
  612: "external link icon",
  613: "Github logo",
  614: "Demo video of the Goudster website",
  615: "Goudster logo",
  616: "Homepage Brasserie Lemmensmolen",
  617: "Lemmensmolen logo",
  618: "Demo video of the Travel Agency website",
  619: "Clear View Escape logo",
  620: "Email icon",
  621: "Phone Belgium icon",
  622: "Phone Spain icon",
  623: "Signal Messenger App logo",
  624: "Skype logo",
  625: "Linked-In logo",
  626: "Twitter logo",
  627: "Codepen logo",
  628: "Copy to clipboard icon",
  629: "Question mark icon",
  630: "Click here to close the modal",
  631: "Casa Pedrera Barcelona",
  632: "Doorbraak logo",
  633: "Codepen profile snapshot",
  634: "Download icon",
};
