// Description: This file contains the text data for the website.
// Basic text strings are numbered 100-499 and are found in html data-txt_id attributes.
// Title attributes are numbered 500-599 and are found in html data-txt_id__title
// Alt attributes are numbered 600-699 and are found in html data-txt_id__alt

export const data_lang_nl = {
  document_lang: "nl",
  document_desc: "Website van Lion Digits, door Joris Raymaekers.",
  document_title: "Lion Digits, web ontwikkeling",
  pseudo_elem_001: "Gekopieerd!",
  100: "nl",
  101: "Nieuwe Titel Hier.",
  102: "Je website is dé weg naar méér klanten en inkomsten",
  103: "met LionDigits ga je sneller en verder.",
  104: "Maak een afspraak",
  105: "Pixel-perfecte web app ontwikkeling met aandacht voor best-practices in HTML5 / CSS3/ JS / ReactJS Native en meer.",
  106: "Bouwen van krachtige, op maat gemaakte Wordpress content management systemen & e-commerce webwinkels.",
  107: " Prestatie- en SEO-optimalisatie voor sneller laden, meer conversies en optimale zoekprestaties",
  108: "Slimme ondernemers",
  109: "beseffen het belang van een goed ontworpen aanwezigheid op het web, hoe die presentatie ervoor zorgt dat hun doelgroep wordt bereikt en dat de daaruit volgende leads worden omgezet in",
  110: "extra inkomsten",
  111: "Joris Raymaekers",
  112: "heeft een ruime ervaring in het creëren van relevante en gebruiksvriendelijke web applicaties en helpt graag ondernemers om hun doelen te overtreffen. Neem contact op of boek meteen een vrijblijvende online consultatie.",
  113: "Geïnteresseerd? Maak een afspraak",
  114: "Boek meteen vrijblijvend een gesprek online om te verkennen hoe we het  beste kunnen samenwerken.",
  115: "Meer weten over wie ik ben?",
  116: "Op zoek naar technische competenties in JavaScript, TypeScript, NodeJs, ReactJs en meer...?",
  117: "Lees meer...",
  118: "Voorbeelden van dingen die we al maakten...",
  119: "Web applicatie voor het oplijsten van kampeerplaatsen in Catalonië. Dit project beslaat de ganse 'web stack': een backend API, een desktop web app en een mobile app voor iOS en Android.",
  120: "live website",
  121: "technische fiche",
  122: "Voor het biermerk Goudster uit Halen werd een nieuwe website gebouwd met een handig overzicht van de lange geschiedenis van de brouwerij en een module voor online bestellingen.",
  123: "Het klantenbestand van Brasserie Lemmensmolen in Beverlo kreeg een stevige boost na het lanceren van een elegante website met een module voor online reserveren.",
  124: "Showcase website voor reisbureau Clear View Escape",
  125: "Algemene voorwaarden",
  126: "Privacy-beleid",
  127: "Deze site is ook bereikbaar via een Tor Onion URL:",
  128: "Versleutelde communicatie",
  129: "Je kan mij zowel gewone standaard (e-mail)berichten sturen als versleutelde berichten. De meest gebruiksvriendelijke manier om mij",
  130: "versleutelde",
  131: "berichten te versturen is via de",
  132: "Gebruik je net als ik",
  133: "voor je e-mail? Dan hoef je niets bijzonder te doen en worden je berichten automatisch versleuteld.",
  134: "Gebruik je een andere e-mail dienstverlener dan kan je gebruik maken van mijn publieke sleutel om een bericht te versleutelen. De 16 digits die je ziet op de homepagina is een",
  135: "digitale vingerafdruk",
  136: "De volledige publieke sleutel kan je hieronder downloaden of kopiëren via het klembord.",
  137: "Niet vertrouwd met PGP? Wil je meer leren over het versleutelen van berichten of bestanden?",
  138: "Lees hier",
  139: "een introductie",
  140: "Of boek een afspraak met mij en ik help je op weg.",
  141: "Download Publieke Sleutel",
  142: "Publieke Sleutel Kopiëren",
  143: "TOR ondersteuning",
  144: "Deze website is ook beschikbaar via het TOR (The Onion Router) netwerk. Verbindingen via TOR maken het zeer lastig om jouw locatie en identiteit te achterhalen. Je wint aan privacy, maar het laden van de site kan vertraging oplopen.",
  145: "Om te verbinden via Tor gebruik je een speciale browser,",
  146: ", of een browser met ingebouwde ondersteuning voor Onion adressen zoals",
  147: "De link naar Lion Digits is vervolgens:",
  501: "Foto van Joris Raymaekers",
  502: "JavaScript",
  503: "ReactJs",
  504: "TypeScript",
  505: "NodeJs",
  506: "Demo video van de Catacamp website",
  507: "Bezoek de Catacamp website",
  508: "Bekijk de code op GitHub",
  509: "Demo video van de Goudster website",
  510: "Bezoek de website van Goudster",
  511: "Homepagina Brasserie Lemmensmolen",
  512: "Bezoek de website van Brasserie Lemmensmolen",
  513: "Demo video van de Travel Agency website",
  514: "Bezoek de website van Clear View Escape",
  515: "Email Joris Raymaekers",
  516: "Bel mij vanuit België",
  517: "Bel mij vanuit Spanje",
  518: "Contacteer mij via de Signal Messenger App",
  519: "Contacteer mij via Skype",
  520: "Bekijk mijn profiel op Linked-In",
  521: "Bekijk mijn profiel op Twitter",
  522: "Bekijk de code die ik schrijf op Github",
  523: "Bekijk mijn visuele creaties op Codepen",
  524: "Kopiëren naar klembord",
  525: "Wat is dit?",
  526: "PGP introductie artikel",
  527: "Home",
  528: "Bezoek het MS-DOS Games Archive",
  529: "Lees het privacy-beleid",
  530: "Ondernemingsnummer",
  600: "Lion Digits logo",
  601: "Vertalen icoon",
  602: "Driehoek icoon",
  603: "Pyramide icoon",
  604: "Zandloper icoon",
  605: "Foto van Joris Raymaekers",
  606: "JavaScript logo",
  607: "ReactJs logo",
  608: "TypeScript logo",
  609: "NodeJs logo",
  610: "Demo video van de Catacamp website",
  611: "Catacamp logo",
  612: "externe link icoon",
  613: "Github logo",
  614: "Demo video van de Goudster website",
  615: "Goudster logo",
  616: "Homepagina Brasserie Lemmensmolen",
  617: "Lemmensmolen logo",
  618: "Demo video van de Travel Agency website",
  619: "Clear View Escape logo",
  620: "Email icoon",
  621: "Telefoon België icoon",
  622: "Telefoon Spanje icoon",
  623: "Signal Messenger App logo",
  624: "Skype logo",
  625: "Linked-In logo",
  626: "Twitter logo",
  627: "Codepen logo",
  628: "Kopiëren naar klembord icoon",
  629: "Vraagteken icoon",
  630: "Klik hier om de modal te sluiten",
  631: "Casa Pedrera Barcelona",
  632: "Doorbraak logo",
  633: "Codepen profiel snapshot",
  634: "Download icoon",
};

export const data_lang_en = {
  document_lang: "en",
  document_title: "Lion Digits, web development",
  document_desc: "Website Lion Digits, by Joris Raymaekers.",
  pseudo_elem_001: "Copied!",
  100: "en",
  101: "New Title Here.",
  102: "Your online presence is the gateway to more customers and revenue",
  103: "go further with Lion Digits.",
  104: "Book a meeting",
  105: "Pixel-perfect web app development with special attention for best-practices in HTML5 / CSS3/ JS / ReactJS Native and more.",
  106: "Building powerful, custom-made Wordpress content management systems & e-commerce webshops.",
  107: "Performance and SEO optimization for faster loading, more conversions and optimal search performance",
  108: "Smart entrepreneurs",
  109: "realize the importance of a well-designed web presence, how that presentation ensures that their target audience is reached and that the resulting leads are converted into",
  110: "extra revenue",
  111: "Joris Raymaekers",
  112: "has a wealth of experience in creating relevant and user-friendly web applications and is eager to help entrepreneurs exceed their goals. Get in touch or immediately book your free online consultation.",
  113: "Interested? Book a meeting",
  114: "Book a free online consultation now and let's explore in a quick video chat how we can work together.",
  115: "Want to know more about me?",
  116: "Looking for someone with technical skills in JavaScript, TypeScript, NodeJs, ReactJs and more...?",
  117: "Read more...",
  118: "Examples of things we've built...",
  119: "Web application for listing camping sites in Catalonia. This project covers the entire 'web stack': a backend API, a desktop web app and a mobile app for iOS and Android.",
  120: "live website",
  121: "technical details",
  122: "A modern website was built for the beer brand Goudster from Halen, including an insightful overview of the long history of the brewery and a module for online orders.",
  123: "The customer base of Brasserie Lemmensmolen in Beverlo got a serious boost after launching an elegant website with an online reservation module.",
  124: "Showcase website for travel agency Clear View Escape",
  125: "General terms and conditions",
  126: "Privacy policy",
  127: "This site can also be reached via a Tor Onion URL:",
  128: "Encrypted Communication",
  129: "You can send me standard (email) messages as well as encrypted messages. The most user-friendly way to send me",
  130: "encrypted",
  131: "messages is via the",
  132: "Are you using",
  133: "for your email, just like me? Then you don't have to do anything special, your messages to me are automatically encrypted.",
  134: "If you use another email service provider, you can use my public key to encrypt a message. The 16 digits you see on the homepage is a",
  135: "digital fingerprint",
  136: "The full public key can be downloaded below or copied via the clipboard.",
  137: "Not familiar with PGP? Want to learn more about encrypting messages or files?",
  138: "Read",
  139: "the introduction on PGP encryption.",
  140: "Or book an appointment with me and I will help you on your way.",
  141: "Download Public Key",
  142: "Copy Public Key",
  143: "TOR support",
  144: "This website is also available via the TOR (The Onion Router) network. Connections via TOR make it very difficult to trace your location and identity. You gain privacy, but the loading of the site may be slower.",
  145: "To connect via Tor you have to use a special browser,",
  146: ", or a browser with built-in support for Onion addresses like",
  147: "The link to Lion Digits is then:",
  501: "Foto of Joris Raymaekers",
  502: "JavaScript",
  503: "ReactJs",
  504: "TypeScript",
  505: "NodeJs",
  506: "Demo video of the Catacamp website",
  507: "Visit the Catacamp website",
  508: "View the code on GitHub",
  509: "Demo video of the Goudster website",
  510: "Visit the Goudster website",
  511: "Homepage Brasserie Lemmensmolen",
  512: "Visit the website of Brasserie Lemmensmolen",
  513: "Demo video of the Travel Agency website",
  514: "Visit the website of Clear View Escape",
  515: "Email Joris Raymaekers",
  516: "Call me from Belgium",
  517: "Call me from Spain",
  518: "Contact me via the Signal Messenger App",
  519: "Contact me via Skype",
  520: "View my profile on Linked-In",
  521: "View my profile on Twitter",
  522: "View the code I write on Github",
  523: "View my visual creations on Codepen",
  524: "Copy to clipboard",
  525: "What is this?",
  526: "PGP introduction article",
  527: "Home",
  528: "Visit the MS-DOS Games Archive",
  529: "Read the privacy policy",
  530: "Registered Company number",
  600: "Lion Digits logo",
  601: "Translate icon",
  602: "Triangle icon",
  603: "Pyramid icon",
  604: "Sandglass icon",
  605: "Foto of Joris Raymaekers",
  606: "JavaScript logo",
  607: "ReactJs logo",
  608: "TypeScript logo",
  609: "NodeJs logo",
  610: "Demo video of the Catacamp website",
  611: "Catacamp logo",
  612: "external link icon",
  613: "Github logo",
  614: "Demo video of the Goudster website",
  615: "Goudster logo",
  616: "Homepage Brasserie Lemmensmolen",
  617: "Lemmensmolen logo",
  618: "Demo video of the Travel Agency website",
  619: "Clear View Escape logo",
  620: "Email icon",
  621: "Phone Belgium icon",
  622: "Phone Spain icon",
  623: "Signal Messenger App logo",
  624: "Skype logo",
  625: "Linked-In logo",
  626: "Twitter logo",
  627: "Codepen logo",
  628: "Copy to clipboard icon",
  629: "Question mark icon",
  630: "Click here to close the modal",
  631: "Casa Pedrera Barcelona",
  632: "Doorbraak logo",
  633: "Codepen profile snapshot",
  634: "Download icon",
};
